contact_links:
  - name: Troubleshooting docs & FAQ
    url: https://docs.mau.fi/bridges/general/troubleshooting.html
    about: Check this first if you're having problems setting up the bridge.
  - name: Support room
    url: https://matrix.to/#/#telegram:maunium.net
    about: For setup issues not answered by the troubleshooting docs, ask in the Matrix room.
